// Çok dilli metin konfigürasyonu
const translations = {
    tr: {
        // Header
        "header.title": "Diyanet Mevlana Moske",

        // Navigation
        "nav.home": "Ana Sayfa",
        "nav.about": "Hakkımızda",
        "nav.construction": "Cami İnşaatı",
        "nav.membership": "Üyelik",
        "nav.contact": "İletişim",
        "nav.prayer": "Namaz Vakitleri",

        // Page Titles
        "page.home.title": "Diyanet Mevlana Moske",
        "page.about.title": "Hakkımızda - Diyanet Mevlana Moske",
        "page.construction.title": "Cami İnşaatı - Diyanet Mevlana Moske",
        "page.membership.title": "Üyelik - Diyanet Mevlana Moske",
        "page.contact.title": "İletişim - Diyanet Mevlana Moske",
        "page.prayer.title": "Namaz Vakitleri - Diyanet Mevlana Moske",

        // Home Page
        "home.welcome": "Hoş Geldiniz",
        "home.description": "Diyanet Mevlana Moske'ye hoş geldiniz. Toplumumuza hizmet etmek için buradayız.",

        // Banner
        "banner.title": "Mevlana'nın Işığında",
        "banner.quote": "\"Gel, ne olursan ol, yine gel...\"",
        "banner.description": "Hz. Mevlana'nın evrensel mesajları ile gönüllerde birleşen bir camiyiz.",

        // Vipps Donation
        "vipps.title": "Vipps ile Bağış Yapın",
        "vipps.description": "Norveç'te en kolay ve güvenli bağış yöntemi",
        "vipps.quick.title": "Hızlı ve Güvenli",
        "vipps.number.label": "Vipps Numaramız:",
        "vipps.steps.title": "Nasıl Bağış Yapılır:",
        "vipps.steps.step1": "Vipps uygulamasını açın",
        "vipps.steps.step2": "95074 numarasını arayın",
        "vipps.steps.step3": "Bağış miktarınızı girin",
        "vipps.steps.step4": "Gönder butonuna basın",
        "vipps.button": "📱 Vipps Uygulamasını Aç",
        "vipps.note": "Bağışınız doğrudan cami hesabına ulaşacaktır",
        "vipps.mosque.name": "Diyanet Mevlana Moske",
        "vipps.alert": "Vipps uygulamasını açın ve '95074' numarasını arayın.",
        "vipps.qr.description": "QR kodu tarayın",

        // Donation QR
        "donation.qr.description": "QR kodu tarayarak hızlıca bağış yapabilirsiniz",

        // About Page
        "about.title": "Hakkımızda",
        "about.mission.title": "Misyonumuz",
        "about.mission.text": "Diyanet Mevlana Moske olarak, Norveç'te yaşayan Müslüman topluma hizmet etmek ve İslami değerleri yaşatmak için buradayız.",
        "about.vision.title": "Vizyonumuz",
        "about.vision.text": "Toplumumuzu bir araya getiren, din ve kültür köprüsü olan bir mekân olmayı hedefliyoruz.",
        "about.history.title": "Tarihçemiz",
        "about.history.text": "Camimiz, Norveç'teki Türk ve Müslüman toplumun ihtiyaçlarını karşılamak amacıyla kurulmuştur.",

        // Contact Page
        "contact.title": "İletişim",
        "contact.address.title": "Adres",
        "contact.address.text": "Stavanger Mosque, Dusavikveien 35, 2 etg<br>4007 Stavanger, Norveç",
        "contact.phone.title": "Telefon",
        "contact.phone.text": "+47 40144008",
        "contact.email.title": "E-posta",
        "contact.email.text": "leder@mevlanamoske.no",
        "contact.hours.title": "Açık Olduğumuz Saatler",
        "contact.hours.text": "Pazartesi - Pazar: 09:00 - 21:00",
        "contact.map.title": "Konumumuz",
        "contact.form.title": "Bize Ulaşın",
        "contact.form.name": "Adınız",
        "contact.form.email": "E-posta",
        "contact.form.message": "Mesajınız",
        "contact.form.submit": "Gönder",

        // Membership Page
        "membership.title": "🤝 Cami Üyeliği",
        "membership.subtitle": "Camimize üye olun ve toplumumuzun bir parçası olun",
        "membership.intro.title": "Camimize Hoş Geldiniz",
        "membership.intro.text": "Diyanet Mevlana Moske ailesi olarak sizleri aramızda görmekten büyük mutluluk duyuyoruz. Üye olarak camimizin faaliyetlerinden haberdar olabilir, etkinliklerimize katılabilir ve toplumumuzun güçlü bağlarını daha da sağlamlaştırabilirsiniz.",
        "membership.benefits.title": "Üyelik Avantajları:",
        "membership.benefits.item1": "📧 Düzenli haber bültenleri ve duyurular",
        "membership.benefits.item2": "🎯 Özel etkinlik ve program davetleri",
        "membership.benefits.item3": "📚 Eğitim programlarına öncelikli katılım",
        "membership.benefits.item4": "🤝 Topluluk aktivitelerine aktif katılım",
        "membership.benefits.item5": "💫 Camimizin gelişimine katkıda bulunma",
        "membership.form.title": "📝 Üyelik Başvuru Formu",
        "membership.form.description": "Lütfen aşağıdaki bilgileri eksiksiz olarak doldurun. Kişisel bilgileriniz gizli tutulacak ve sadece cami faaliyetleri için kullanılacaktır.",
        "membership.form.type.label": "İşlem Türü",
        "membership.form.type.new": "Yeni Üyelik",
        "membership.form.type.cancel": "Üyelik İptal",
        "membership.form.firstName.label": "Ad",
        "membership.form.firstName.placeholder": "Adınızı girin",
        "membership.form.lastName.label": "Soyad",
        "membership.form.lastName.placeholder": "Soyadınızı girin",
        "membership.form.email.label": "E-posta",
        "membership.form.email.placeholder": "E-posta adresinizi girin",
        "membership.form.phone.label": "Telefon",
        "membership.form.phone.placeholder": "Telefon numaranızı girin",
        "membership.form.address.label": "Adres",
        "membership.form.address.placeholder": "Tam adresinizi girin",
        "membership.form.newsletter": "E-posta ile haber bültenleri almak istiyorum",
        "membership.form.privacy": "Kişisel verilerimin işlenmesini kabul ediyorum",
        "membership.form.submit": "Başvuru Gönder",
        "membership.form.submit.new": "Başvuru Gönder",
        "membership.form.submit.cancel": "Üyelik İptal",
        "membership.form.success": "Başvurunuz başarıyla alındı! En kısa sürede sizinle iletişime geçeceğiz.",
        "membership.form.success.new": "Başvurunuz başarıyla alındı! En kısa sürede sizinle iletişime geçeceğiz.",
        "membership.form.success.cancel": "Üyelik iptal talebiniz alındı! En kısa sürede işleme konulacaktır.",
        "membership.form.success.submitted": "Formunuz başarıyla gönderildi! En kısa sürede sizinle iletişime geçeceğiz.",
        "membership.contact.title": "📞 İletişim",
        "membership.contact.description": "Üyelikle ilgili sorularınız için bizimle iletişime geçebilirsiniz.",
        "membership.contact.phone": "+47 40144008",
        "membership.contact.email": "leder@mevlanamoske.no",
        "membership.contact.address": "Dusavikveien 35, 2 etg, 4007 Stavanger",

        // Construction Page
        "construction.title": "🕌 Yeni Camimizin İnşaatı",
        "construction.subtitle": "Gelecek nesiller için büyük bir hayır projesi",

        "construction.intro.title": "Aziz Kardeşlerimiz,",
        "construction.intro.text": "Norveç'in Stavanger şehrinde yaşayan Müslümanlar olarak, bundan 40 yıl önce büyük gayret ve fedakârlıkla sahip olduğumuz camimizi zamanla yıkmak zorunda kaldık. Rabbimizin izniyle şimdi daha geniş, daha fonksiyonel ve nesillere fayda sağlayacak bir cami inşa etmeyi arzu ediyoruz. Ancak bu büyük ve hayırlı hizmeti tek başımıza gerçekleştirecek maddi güç bizde yoktur. Bu sebeple dünyanın neresinde olursanız olun tüm hayırsever kardeşlerimizin yardımına muhtacız.",
        "construction.intro.highlight": "Her katkınız, gelecek nesillere kalacak bir mirastır",

        "construction.hadith.arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللَّهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ ﷺ : إِذَا مَاتَ الْإِنْسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلَّا مِنْ ثَلَاثَةٍ: صَدَقَةٍ جَارِيَةٍ، أَوْ عِلْمٍ يُنْتَفَعُ بِهِ، أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ",
        "construction.hadith.source": "(Müslim)",
        "construction.hadith.translation": "\"Âdemoğlu öldüğünde ameli sona erer. Ancak üç şey müstesna: Sadaka-i cariye, kendisinden faydalanılan ilim ve kendisine dua eden hayırlı evlat.\"",
        "construction.hadith.explanation": "Camimizin yapımına yapılacak katkılar sadaka-i cariye hükmünde olacaktır. Bir tuğla bile koysanız, bu hizmetten sürekli pay alacaksınız; amelinizin bereketi devam edecektir.",

        "construction.gallery.title": "🏗️ Proje Görselleri",
        "construction.gallery.subtitle": "Yeni camimizin tasarım ve planları",
        "construction.gallery.item1.title": "Ana Görünüm",
        "construction.gallery.item1.description": "Cami dış görünümü",
        "construction.gallery.item2.title": "İç Mekan Tasarımı",
        "construction.gallery.item2.description": "Cami iç tasarımı",
        "construction.gallery.item3.title": "Yan Görünüm",
        "construction.gallery.item3.description": "Cami yan görünümü",
        "construction.gallery.item4.title": "Genel Plan",
        "construction.gallery.item4.description": "Cami planı",
        "construction.gallery.item5.title": "Detay Görünüm",
        "construction.gallery.item5.description": "Mimari detaylar",
        "construction.gallery.item6.title": "Mescit Alanı",
        "construction.gallery.item6.description": "Namaz alanı",
        "construction.gallery.item7.title": "Çevre Düzenlemesi",
        "construction.gallery.item7.description": "Peyzaj tasarımı",
        "construction.gallery.item8.title": "Ek Tesisler",
        "construction.gallery.item8.description": "Sosyal alanlar",
        "construction.gallery.item9.title": "Gece Görünümü",
        "construction.gallery.item9.description": "Gece aydınlatması",

        "construction.floors.title": "🏢 Proje ve Bölümler",
        "construction.floors.description": "Yeni camimiz 4 katlı olarak planlanmıştır. Hem ibadet hem de eğitim ve sosyal hizmetlerin verileceği bir merkez olacaktır:",
        "construction.floors.floor1.title": "Ana Mescid",
        "construction.floors.floor1.description": "Cemaatin topluca namaz kılacağı geniş ibadet alanı.",
        "construction.floors.floor2.title": "Hanımlar Bölümü",
        "construction.floors.floor2.description": "Hanımlar için ayrı namaz bölümü ve mutfak — topluluk yemekleri ve sosyal etkinlikler için.",
        "construction.floors.floor3.title": "Eğitim Alanları",
        "construction.floors.floor3.description": "3 adet derslik, kütüphane ve kafeterya — gençler ve çocuklar için eğitim faaliyetleri.",
        "construction.floors.floor4.title": "Lojmanlar",
        "construction.floors.floor4.description": "2 adet lojman — imam ve diğer görevli hocalarımız için konaklama.",
        "construction.floors.minaret.title": "Minare",
        "construction.floors.minaret.description": "Camimize şeref katacak minare planlanmıştır.",
        "construction.floors.elevator.title": "Asansör",
        "construction.floors.elevator.description": "Tüm katlara kolay ve engelli ulaşımı sağlamak üzere asansör bulunacaktır.",
        "construction.floors.conclusion": "Bu düzen ile camimiz sadece ibadet mekânı değil, ilim, dayanışma ve toplum hizmeti veren bir merkez olacaktır.",

        "construction.features.title": "🌟 Yeni Camimizin Özellikleri",
        "construction.features.capacity.title": "Geniş Kapasite",
        "construction.features.capacity.description": "Daha fazla cemaatimizi ağırlayabilecek büyük namaz salonu",
        "construction.features.education.title": "Eğitim Alanları",
        "construction.features.education.description": "Çocuklarımız için Kuran kursu ve sınıf odaları",
        "construction.features.facilities.title": "Modern Tesis",
        "construction.features.facilities.description": "Abdest alma yerleri ve sosyal alanlar",
        "construction.features.accessibility.title": "Engelsiz Erişim",
        "construction.features.accessibility.description": "Tüm yaş grupları için uygun tasarım",
        "construction.features.parking.title": "Otopark",
        "construction.features.parking.description": "Geniş araç park alanı",
        "construction.features.community.title": "Toplum Merkezi",
        "construction.features.community.description": "Etkinlikler ve sosyal buluşmalar için alan",

        "construction.donation.title": "🤲 Bu Hayır İşine Katkıda Bulunun",
        "construction.donation.description": "Yeni camimizin inşaatına yapacağınız her katkı, gelecek nesillere kalacak bir emanettir. Rabbimizin rızası için bu mübarek projeye destek olun.",
        "construction.donation.methods.title": "Bağış Yöntemleri:",
        "construction.donation.vipps": "Vipps: 95074",
        "construction.donation.bank": "Banka Havalesi",
        "construction.donation.contact": "Bizimle İletişime Geçin",
        "construction.donation.vipps.btn": "📱 Vipps ile Bağış Yap",
        "construction.donation.contact.btn": "📞 İletişime Geç",
        "construction.donation.qr.text": "QR kodu tarayarak hızlıca bağış yapın",
        "construction.donation.bank.details.title": "💳 Banka Havalesi Bilgileri",
        "construction.donation.bank.name": "Banka:",
        "construction.donation.bank.account": "Konto nr:",
        "construction.donation.bank.description": "Açıklama:",
        "construction.donation.bank.contact": "İletişim: +47 40 14 40 08",

        // Education Navigation
        "nav.education": "Eğitim",
        "nav.education.dershane": "Dershane",
        "nav.education.norwegian": "Norveççe Dersleri",
        "nav.education.quran": "Kuran Kursu",

        // Page Titles
        "page.dershane.title": "Dershane - Diyanet Mevlana Moske",
        "page.norwegian.title": "Norveççe Dersleri - Diyanet Mevlana Moske",
        "page.quran.title": "Kuran Kursu - Diyanet Mevlana Moske",

        // Dershane Page
        "dershane.title": "📚 Dershane",
        "dershane.subtitle": "Öğrencilerimiz için özel ders ve çalışma ortamı",
        "dershane.intro.title": "Dershane Programımız",
        "dershane.intro.description": "Camimizde bulunan dershane, öğrencilerimizin akademik başarılarını desteklemek amacıyla düzenlenmiştir. Huzurlu ve sessiz bir ortamda çalışma imkanı sunan dershanemizde, öğrenciler hem bireysel çalışabilir hem de grup halinde derslerini tekrar edebilirler.",
        "dershane.schedule.title": "📅 Ders Programı",
        "dershane.schedule.main.title": "Dershane Saatleri",
        "dershane.schedule.tuesday": "Salı",
        "dershane.schedule.thursday": "Perşembe",
        "dershane.schedule.time": "14:00 - 16:00",
        "dershane.schedule.duration": "Haftada 2 gün",
        "dershane.info.title": "Dershane Özellikleri",
        "dershane.info.feature1": "Sessiz ve huzurlu çalışma ortamı",
        "dershane.info.feature2": "Bireysel çalışma masaları",
        "dershane.info.feature3": "Grup çalışması için uygun alanlar",
        "dershane.info.feature4": "Ders tekrarı ve ödev yapma imkanı",
        "dershane.info.feature5": "Ücretsiz katılım",
        "dershane.gallery.title": "🖼️ Dershane Görüntüleri",
        "dershane.gallery.subtitle": "Öğrencilerimizin çalıştığı alanlardan görüntüler",
        "dershane.gallery.item1.title": "Çalışma Alanı",
        "dershane.gallery.item1.description": "Öğrenciler için düzenlenmiş bireysel çalışma masaları",
        "dershane.gallery.item2.title": "Grup Çalışma Alanı",
        "dershane.gallery.item2.description": "Grup halinde çalışma için düzenlenmiş alan",
        "dershane.gallery.item3.title": "Sessiz Çalışma Ortamı",
        "dershane.gallery.item3.description": "Konsantre çalışma için ideal sessiz ortam",
        "dershane.registration.title": "🎯 Kayıt ve Katılım",
        "dershane.registration.description": "Dershane programımıza katılmak için önceden kayıt yaptırmanız gerekmektedir. Kayıt olmak veya daha fazla bilgi almak için bizimle iletişime geçebilirsiniz.",
        "dershane.registration.feature1": "Kolay kayıt işlemi",
        "dershane.registration.feature2": "Ücretsiz katılım",
        "dershane.registration.feature3": "Tüm yaş grupları",
        "dershane.contact.phone": "Telefon: +47 40 14 40 08",
        "dershane.contact.email": "E-posta Gönder",
        "dershane.visual.title": "Akademik Başarı",
        "dershane.visual.description": "Dershanemizde çalışan öğrencilerimizin akademik başarıları artmaktadır",

        // Norwegian Lessons Page
        "norwegian.title": "🇳🇴 Norveççe Dersleri",
        "norwegian.subtitle": "Norveç'te yaşam için temel dil becerileri",
        "norwegian.intro.title": "Norveççe Öğrenme Programımız",
        "norwegian.intro.description": "Norveç'te yaşayan toplumumuzun günlük yaşamlarını kolaylaştırmak amacıyla düzenlenen Norveççe dersleri, temel seviyeden başlayarak günlük konuşma becerilerini geliştirmeyi hedeflemektedir. Deneyimli öğretmenlerimiz eşliğinde, interaktif yöntemlerle dil öğrenme sürecini eğlenceli hale getiriyoruz.",
        "norwegian.schedule.title": "📅 Ders Programı",
        "norwegian.schedule.main.title": "Norveççe Ders Saatleri",
        "norwegian.schedule.monday": "Pazartesi",
        "norwegian.schedule.wednesday": "Çarşamba",
        "norwegian.schedule.time": "12:00 - 15:00",
        "norwegian.schedule.duration": "Haftada 2 gün",
        "norwegian.info.title": "Ders İçerikleri",
        "norwegian.info.feature1": "Temel konuşma becerileri",
        "norwegian.info.feature2": "Günlük yaşam kelime dağarcığı",
        "norwegian.info.feature3": "Resmi kurumlarda iletişim",
        "norwegian.info.feature4": "İş hayatında kullanılacak dil",
        "norwegian.info.feature5": "Dinleme ve anlama becerileri",
        "norwegian.gallery.title": "🖼️ Sınıf Görüntüleri",
        "norwegian.gallery.subtitle": "Norveççe derslerinden görüntüler",
        "norwegian.gallery.item1.title": "Dil Sınıfı",
        "norwegian.gallery.item1.description": "Norveççe öğretimi için düzenlenmiş sınıf ortamı",
        "norwegian.gallery.item2.title": "İnteraktif Öğrenme",
        "norwegian.gallery.item2.description": "Konuşma pratiği ve grup çalışmaları",
        "norwegian.gallery.item3.title": "Öğrenme Materyalleri",
        "norwegian.gallery.item3.description": "Modern öğretim araçları ve kaynakları",
        "norwegian.levels.title": "📊 Seviye Programları",
        "norwegian.levels.beginner.title": "Başlangıç Seviyesi",
        "norwegian.levels.intermediate.title": "Orta Seviye",
        "norwegian.levels.advanced.title": "İleri Seviye",
        "norwegian.registration.title": "🎯 Kayıt ve Katılım",
        "norwegian.registration.description": "Norveççe derslerimize katılmak için önceden kayıt yaptırmanız gerekmektedir. Seviye tespit testi yapılarak size uygun sınıfa yerleştirme işlemi gerçekleştirilir.",
        "norwegian.registration.feature1": "Seviye tespit testi",
        "norwegian.registration.feature2": "Küçük sınıf grupları",
        "norwegian.registration.feature3": "Katılım sertifikası",
        "norwegian.contact.phone": "Telefon: +47 40 14 40 08",
        "norwegian.contact.email": "E-posta Gönder",
        "norwegian.visual.title": "Kültürler Arası Köprü",
        "norwegian.visual.description": "Dil öğrenerek Norveç toplumuna daha iyi entegre olun",

        // Quran Course Page
        "quran.title": "📖 Kuran Kursu",
        "quran.subtitle": "Kuran-ı Kerim öğretimi ve tecvid dersleri",
        "quran.intro.title": "Kuran-ı Kerim Öğretim Programımız",
        "quran.intro.description": "Kuran-ı Kerim öğretimi amacıyla düzenlenen kursumuzda, çocuklarımız ve gençlerimiz için yaş gruplarına uygun Kuran okuma, tecvid kuralları ve temel din bilgileri dersleri verilmektedir. Deneyimli hocalarımız eşliğinde, geleneksel öğretim yöntemleri ile modern eğitim tekniklerini harmanlayarak etkili bir öğrenme ortamı sunuyoruz.",
        "quran.schedule.title": "📅 Ders Programı",
        "quran.schedule.main.title": "Kuran Kursu Saatleri",
        "quran.schedule.saturday": "Cumartesi",
        "quran.schedule.sunday": "Pazar",
        "quran.schedule.time": "12:00 - 16:00",
        "quran.schedule.duration": "Haftada 2 gün",
        "quran.info.title": "Ders İçerikleri",
        "quran.info.feature1": "Kuran-ı Kerim okuma öğretimi",
        "quran.info.feature2": "Tecvid kuralları ve makamlar",
        "quran.info.feature3": "Temel din bilgileri",
        "quran.info.feature4": "Namaz sureleri ve duaları",
        "quran.info.feature5": "İslam ahlakı ve adabı",
        "quran.gallery.title": "🖼️ Kuran Kursu Görüntüleri",
        "quran.gallery.subtitle": "Öğrencilerimizin Kuran öğrenirken çekilmiş fotoğrafları",
        "quran.gallery.item1.title": "Kuran Dersleri",
        "quran.gallery.item1.description": "Öğrencilerimizin Kuran-ı Kerim okuma dersleri",
        "quran.gallery.item2.title": "Tecvid Eğitimi",
        "quran.gallery.item2.description": "Tecvid kuralları ve doğru okuma teknikleri",
        "quran.gallery.item3.title": "Grup Dersleri",
        "quran.gallery.item3.description": "Yaş gruplarına göre organize edilmiş dersler",
        "quran.levels.title": "👥 Yaş Grupları",
        "quran.levels.children.title": "Çocuk Grubu (6-12 yaş)",
        "quran.levels.youth.title": "Genç Grubu (13-18 yaş)",
        "quran.levels.adult.title": "Yetişkin Grubu (18+ yaş)",
        "quran.benefits.title": "🌟 Kuran Öğrenmenin Faydaları",
        "quran.benefits.spiritual.title": "Manevi Gelişim",
        "quran.benefits.spiritual.description": "Kuran öğrenmek, manevi gelişim ve Allah'a yakınlık sağlar",
        "quran.benefits.mental.title": "Zihinsel Gelişim",
        "quran.benefits.mental.description": "Hafıza güçlendirme ve konsantrasyon artırma",
        "quran.benefits.moral.title": "Ahlaki Gelişim",
        "quran.benefits.moral.description": "İslami değerler ve güzel ahlak kazanımı",
        "quran.benefits.social.title": "Sosyal Bağ",
        "quran.benefits.social.description": "Toplumla daha güçlü bağlar kurma",
        "quran.registration.title": "🎯 Kayıt ve Katılım",
        "quran.registration.description": "Kuran kursumuz tüm yaş gruplarına açıktır. Kayıt olmak için bizimle iletişime geçebilir, çocuğunuzun veya kendinizin seviyesine uygun sınıfa dahil olabilirsiniz.",
        "quran.registration.feature1": "6 yaş ve üzeri",
        "quran.registration.feature2": "Ücretsiz eğitim",
        "quran.registration.feature3": "Kişisel ilerleme takibi",
        "quran.contact.phone": "Telefon: +47 40 14 40 08",
        "quran.contact.email": "E-posta Gönder",
        "quran.visual.title": "Din Eğitimi",
        "quran.visual.description": "Çocuklarımızın dini kimlik ve değerlerini geliştirmelerine destek oluyoruz",

        "construction.timeline.title": "📅 Proje Zaman Çizelgesi",
        "construction.timeline.planning.title": "Planlama Aşaması",
        "construction.timeline.planning.description": "Proje tasarımı ve izinler tamamlandı",
        "construction.timeline.planning.date": "2024",
        "construction.timeline.construction.title": "İnşaat Aşaması",
        "construction.timeline.construction.description": "Şu anda fon toplama ve hazırlık aşamasındayız",
        "construction.timeline.construction.date": "2025",
        "construction.timeline.opening.title": "Açılış",
        "construction.timeline.opening.description": "Yeni camimizin açılışı planlanıyor",
        "construction.timeline.opening.date": "2026",

        // Donation Terms
        "donation.terms.title": "Bağış Şartları",
        "donation.terms.short.description": "Değerli üyelerimiz, Norveç'te onaylı bir dinî topluluk veya inanç kuruluşuna bağış yaptığınızda vergi indirimi alabilirsiniz. 🔸 Maksimum indirim: Yılda 25.000 NOK'a kadar. 🔸 Asgari tutar: En az 500 NOK. 🔸 Kişisel bilgiler: Tam adınızı ve doğum numaranızı (11 haneli) vermeniz gerekir. 🔸 Otomatik bildirim: Bağışınız Skatteetaten'e rapor edilir ve indirim otomatik olarak vergi bildiriminize yansır. Camimize yapacağınız bağışla hem topluluğumuzu güçlendirmiş olacaksınız, hem de devletin sağladığı vergi indirimi avantajından yararlanacaksınız. 🤲 Desteğiniz hem manevi hem de maddi kazanç getirir.",
        "donation.terms.button": "Bağış Şartlarını Görüntüle",
        "donation.terms.intro": "Bu şartlar, bağışçılardan camiye yapılan bağışları düzenlemektedir. Bir bağış yaparak, bağışçı olarak aşağıdaki şartları kabul etmiş olursunuz:",

        "donation.terms.purpose.title": "1. Bağışın Amacı",
        "donation.terms.purpose.content": "Cami tarafından alınan bağışlar yalnızca caminin faaliyetlerini desteklemek için kullanılacaktır, bunlar şunları içerir ancak bunlarla sınırlı değildir:",
        "donation.terms.purpose.item1": "Cami tesislerinin işletilmesi ve bakımı.",
        "donation.terms.purpose.item2": "Dini ve sosyal etkinlikler.",
        "donation.terms.purpose.item3": "Cami tarafından onaylanan hayır işleri.",

        "donation.terms.voluntary.title": "2. Gönüllülük ve Karşılık Verilmemesi",
        "donation.terms.voluntary.content": "Camiye yapılan bağışlar gönüllü katkılardır. Önceden açıkça anlaşılmadığı sürece, bağış yapmanın sonucu olarak herhangi bir karşılık veya hak verilmez.",

        "donation.terms.payment.title": "3. Ödeme Yöntemleri",
        "donation.terms.payment.content": "Bağışlar aşağıdaki yöntemlerle yapılabilir:",
        "donation.terms.payment.item1": "Banka havalesi.",
        "donation.terms.payment.item2": "Vipps veya benzer ödeme hizmetleri.",
        "donation.terms.payment.item3": "Şahsen gelip nakit ödeme.",
        "donation.terms.payment.note": "Cami, bağışın transferi ile ilgili olarak ortaya çıkan herhangi bir ücret veya gecikme için sorumluluk kabul etmez.",

        "donation.terms.confirmation.title": "4. Alındı Onayı",
        "donation.terms.confirmation.content": "İstenirse bağışçılara bağış için bir onay gönderilecektir. Onay, bağış miktarı, alınma tarihi ve bağışın kullanılacağı amaç hakkında bilgi içerebilir.",

        "donation.terms.usage.title": "5. Bağışın Kullanımı",
        "donation.terms.usage.content": "Cami, fonları cami yönetim kurulu tarafından belirlenen önceliklere uygun olarak dağıtma hakkını saklı tutar. Belirli bir amaca ayrılan bağışlar, mümkün olduğunca belirtilen amaç için kullanılacaktır.",

        "donation.terms.refund.title": "6. Geri Ödeme",
        "donation.terms.refund.content": "Bağışlar kural olarak geri ödenemez. Transfer sırasında bir hata oluşursa, bağışçıların durumu düzeltmek için derhal cami ile iletişime geçmelerini rica ederiz.",

        "donation.terms.privacy.title": "7. Gizlilik",
        "donation.terms.privacy.content": "Bağışlarla ilgili olarak toplanan kişisel bilgiler, geçerli veri koruma mevzuatına uygun olarak işlenecektir. Bilgiler yalnızca bağışın yönetimi için kullanılacak ve rıza olmadan üçüncü taraflarla paylaşılmayacaktır.",

        "donation.terms.changes.title": "8. Şartlarda Değişiklik",
        "donation.terms.changes.content": "Cami bu şartları değiştirme hakkını saklı tutar. Herhangi bir değişiklik caminin web sitesinde yayınlanacak veya uygun başka bir şekilde duyurulacaktır.",

        "donation.terms.contact.title": "9. İletişim Bilgileri",
        "donation.terms.contact.content": "Bağışlar veya bu şartlar hakkında sorularınız için cami ile şu bilgilerden iletişime geçebilirsiniz:",
        "donation.terms.contact.email": "E-posta: leder@Mevlanamoske.no",
        "donation.terms.contact.phone": "Telefon: +47 40144008",
        "donation.terms.contact.address": "Adres: Verksgt 41 4013 Stavanger",
        "donation.terms.contact.org": "Organizasyon Numarası: 971 490 942",

        "donation.terms.acceptance": "Bir bağış yaparak, bu şartları okuduğunuzu ve anladığınızı ve bunları tamamen kabul ettiğinizi onaylarsınız.",

        // Donation Terms PDF
        "donation.terms.pdf.fallback": "PDF görüntüleyiciniz bu dosyayı desteklemiyor.",
        "donation.terms.pdf.download": "Buraya tıklayarak indirin",
        "donation.terms.pdf.open": "Yeni Sekmede Aç",
        "donation.terms.pdf.download.btn": "İndir",

        // Prayer Times
        "prayer.page.title": "Namaz Vakitleri",
        "prayer.page.subtitle": "Stavanger - Norveç için günlük namaz vakitleri",
        "prayer.location": "Stavanger, Norveç",
        "prayer.today.title": "Bugünün Namaz Vakitleri",
        "prayer.fajr": "İmsak",
        "prayer.sunrise": "Güneş",
        "prayer.dhuhr": "Öğle",
        "prayer.asr": "İkindi",
        "prayer.maghrib": "Akşam",
        "prayer.isha": "Yatsı",
        "prayer.next.title": "Sıradaki Namaz",
        "prayer.weekly.title": "Haftalık Namaz Vakitleri",
        "prayer.table.date": "Tarih",
        "prayer.table.fajr": "İmsak",
        "prayer.table.sunrise": "Güneş",
        "prayer.table.dhuhr": "Öğle",
        "prayer.table.asr": "İkindi",
        "prayer.table.maghrib": "Akşam",
        "prayer.table.isha": "Yatsı",
        "prayer.notes.title": "Önemli Notlar",
        "prayer.notes.calculation": "Vakitler Diyanet İşleri hesaplama yöntemine göre belirlenmiştir.",
        "prayer.notes.location": "Stavanger koordinatları: 58.9937° K, 5.7275° D",
        "prayer.notes.accuracy": "Vakitler yaklaşık olup, ±2 dakika tolerans gösterebilir.",
        "prayer.notes.update": "Vakitler otomatik olarak güncellenmektedir.",

        // Footer
        "footer.welcome": "Diyanet Mevlana Moske'ye Hoş Geldiniz",
        "footer.description": "Stavanger'e bulunan Diyanet Mevlana Moske olarak Müslüman toplumumuza hizmet etmekten gurur duyuyoruz.",
        "footer.org.number": "Org.nr: 971 490 942",
        "footer.quick.links": "Hızlı Linkler",
        "footer.support": "Destek",
        "footer.vipps.donation": "Vipps ile Bağış: 95074",
        "footer.mosque.name": "Diyanet Mevlana Moske",
        "footer.contact.title": "İletişim",
        "footer.contact.phone": "Telefon:",
        "footer.contact.email": "E-posta:",
        "footer.contact.address": "Adres:",
        "footer.contact.address.text": "Dusavikveien 35 4007, Stavanger, Norway",
        "footer.map.title": "Konum",
        "footer.copyright": "© 2025 Diyanet Mevlana Moske. Tüm hakları saklıdır."
    },

    no: {
        // Header
        "header.title": "Diyanet Mevlana Moske",

        // Navigation
        "nav.home": "Hjem",
        "nav.about": "Om oss",
        "nav.construction": "Moské Byggeri",
        "nav.membership": "Medlemskap",
        "nav.contact": "Kontakt",
        "nav.prayer": "Bønnetider",

        // Page Titles
        "page.home.title": "Diyanet Mevlana Moske",
        "page.about.title": "Om oss - Diyanet Mevlana Moske",
        "page.construction.title": "Moské Byggeri - Diyanet Mevlana Moske",
        "page.membership.title": "Medlemskap - Diyanet Mevlana Moske",
        "page.contact.title": "Kontakt - Diyanet Mevlana Moske",
        "page.prayer.title": "Bønnetider - Diyanet Mevlana Moske",

        // Home Page
        "home.welcome": "Velkommen",
        "home.description": "Velkommen til Diyanet Mevlana Moske. Vi er her for å tjene vårt samfunn.",

        // Banner
        "banner.title": "I Mevlanas lys",
        "banner.quote": "\"Kom, kom, uansett hvem du er, kom igjen...\"",
        "banner.description": "Vi er en moske som forenes i hjerter med Mevlanas universelle budskap.",

        // Vipps Donation
        "vipps.title": "Doner med Vipps",
        "vipps.description": "Den enkleste og sikreste donasjonsmetoden i Norge",
        "vipps.quick.title": "Raskt og Sikkert",
        "vipps.number.label": "Vårt Vipps-nummer:",
        "vipps.steps.title": "Slik donerer du:",
        "vipps.steps.step1": "Åpne Vipps-appen",
        "vipps.steps.step2": "Søk etter nummer 95074",
        "vipps.steps.step3": "Skriv inn donasjonsbeløpet",
        "vipps.steps.step4": "Trykk send",
        "vipps.button": "📱 Åpne Vipps-appen",
        "vipps.note": "Din donasjon går direkte til moskeen",
        "vipps.mosque.name": "Diyanet Mevlana Moske",
        "vipps.alert": "Åpne Vipps-appen og søk etter '95074'.",
        "vipps.qr.description": "Skann QR-koden",

        // Donation QR
        "donation.qr.description": "Skann QR-koden for rask donasjon",

        // Education Navigation
        "nav.education": "Utdanning",
        "nav.education.dershane": "Studiesal",
        "nav.education.norwegian": "Norskundervisning",
        "nav.education.quran": "Korankurs",

        // Page Titles
        "page.dershane.title": "Studiesal - Diyanet Mevlana Moske",
        "page.norwegian.title": "Norskundervisning - Diyanet Mevlana Moske",
        "page.quran.title": "Korankurs - Diyanet Mevlana Moske",

        // Dershane Page
        "dershane.title": "📚 Studiesal",
        "dershane.subtitle": "Spesiell undervisning og studiemiljø for våre studenter",
        "dershane.intro.title": "Vårt studiesalprogram",
        "dershane.intro.description": "Studiesalen ved vår moske er organisert for å støtte studentenes akademiske suksess. I et fredelig og stille miljø tilbyr studiesalen våre studenter muligheten til å studere både individuelt og i grupper for å gjenta leksjonene sine.",
        "dershane.schedule.title": "📅 Timeplan",
        "dershane.schedule.main.title": "Studiesaltimer",
        "dershane.schedule.tuesday": "Tirsdag",
        "dershane.schedule.thursday": "Torsdag",
        "dershane.schedule.time": "14:00 - 16:00",
        "dershane.schedule.duration": "2 dager i uken",
        "dershane.info.title": "Studiesalfunksjoner",
        "dershane.info.feature1": "Stille og fredelig studiemiljø",
        "dershane.info.feature2": "Individuelle studiebord",
        "dershane.info.feature3": "Egnede områder for gruppestudier",
        "dershane.info.feature4": "Mulighet for lekserepetisjon og lekser",
        "dershane.info.feature5": "Gratis deltakelse",
        "dershane.gallery.title": "🖼️ Studiesalbilder",
        "dershane.gallery.subtitle": "Bilder fra områdene der studentene våre jobber",
        "dershane.gallery.item1.title": "Studieområde",
        "dershane.gallery.item1.description": "Individuelle studiebord arrangert for studenter",
        "dershane.gallery.item2.title": "Gruppestudieområde",
        "dershane.gallery.item2.description": "Område arrangert for gruppestudier",
        "dershane.gallery.item3.title": "Stille studiemiljø",
        "dershane.gallery.item3.description": "Ideelt stille miljø for konsentrert studium",
        "dershane.registration.title": "🎯 Registrering og deltakelse",
        "dershane.registration.description": "For å delta i studiesalprogrammet vårt må du registrere deg på forhånd. Du kan kontakte oss for å registrere deg eller få mer informasjon.",
        "dershane.registration.feature1": "Enkel registreringsprosess",
        "dershane.registration.feature2": "Gratis deltakelse",
        "dershane.registration.feature3": "Alle aldersgrupper",
        "dershane.contact.phone": "Telefon: +47 40 14 40 08",
        "dershane.contact.email": "Send e-post",
        "dershane.visual.title": "Akademisk suksess",
        "dershane.visual.description": "Studentenes akademiske suksess som studerer i studiesalen vår øker",

        // Norwegian Lessons Page
        "norwegian.title": "🇳🇴 Norskundervisning",
        "norwegian.subtitle": "Grunnleggende språkferdigheter for å leve i Norge",
        "norwegian.intro.title": "Vårt norskopplæringsprogram",
        "norwegian.intro.description": "Norsktimer arrangert for å lette hverdagen til samfunnet vårt som bor i Norge, har som mål å utvikle daglige samtaleferdigheter fra grunnleggende nivå. Med våre erfarne lærere gjør vi språklæringsprosessen morsom med interaktive metoder.",
        "norwegian.schedule.title": "📅 Timeplan",
        "norwegian.schedule.main.title": "Norsk leksjonstimer",
        "norwegian.schedule.monday": "Mandag",
        "norwegian.schedule.wednesday": "Onsdag",
        "norwegian.schedule.time": "12:00 - 15:00",
        "norwegian.schedule.duration": "2 dager i uken",
        "norwegian.info.title": "Leksjonsinnhold",
        "norwegian.info.feature1": "Grunnleggende samtaleferdigheter",
        "norwegian.info.feature2": "Daglig ordforråd",
        "norwegian.info.feature3": "Kommunikasjon i offentlige institusjoner",
        "norwegian.info.feature4": "Språk som skal brukes i arbeidslivet",
        "norwegian.info.feature5": "Lytte- og forståelsesferdigheter",
        "norwegian.gallery.title": "🖼️ Klassebilder",
        "norwegian.gallery.subtitle": "Bilder fra norsktimer",
        "norwegian.gallery.item1.title": "Språkklasserom",
        "norwegian.gallery.item1.description": "Klasseromsmiljø arrangert for norskundervisning",
        "norwegian.gallery.item2.title": "Interaktiv læring",
        "norwegian.gallery.item2.description": "Talepraksis og gruppestudier",
        "norwegian.gallery.item3.title": "Læringsmaterialer",
        "norwegian.gallery.item3.description": "Moderne undervisningsverktøy og ressurser",
        "norwegian.levels.title": "📊 Nivåprogrammer",
        "norwegian.levels.beginner.title": "Nybegynnernivå",
        "norwegian.levels.intermediate.title": "Middels nivå",
        "norwegian.levels.advanced.title": "Avansert nivå",
        "norwegian.registration.title": "🎯 Registrering og deltakelse",
        "norwegian.registration.description": "For å delta i norsktimene våre må du registrere deg på forhånd. Plasseringstest utføres og du blir plassert i klassen som passer ditt nivå.",
        "norwegian.registration.feature1": "Nivåbestemmelsestest",
        "norwegian.registration.feature2": "Små klassegrupper",
        "norwegian.registration.feature3": "Deltakelsessertifikat",
        "norwegian.contact.phone": "Telefon: +47 40 14 40 08",
        "norwegian.contact.email": "Send e-post",
        "norwegian.visual.title": "Bro mellom kulturer",
        "norwegian.visual.description": "Lær språk og integrer deg bedre i det norske samfunnet",

        // Quran Course Page
        "quran.title": "📖 Korankurs",
        "quran.subtitle": "Koranundervisning og tajwid-timer",
        "quran.intro.title": "Vårt Koran-undervisningsprogram",
        "quran.intro.description": "I kurset vårt arrangert for undervisning av Koranen, tilbys Koranlesing, tajwid-regler og grunnleggende religionsundervisning for aldersgrupper egnet for våre barn og ungdom. Med våre erfarne lærere tilbyr vi et effektivt læringsmiljø ved å kombinere tradisjonelle undervisningsmetoder med moderne undervisningsteknikker.",
        "quran.schedule.title": "📅 Timeplan",
        "quran.schedule.main.title": "Korankurstimer",
        "quran.schedule.saturday": "Lørdag",
        "quran.schedule.sunday": "Søndag",
        "quran.schedule.time": "12:00 - 16:00",
        "quran.schedule.duration": "2 dager i uken",
        "quran.info.title": "Leksjonsinnhold",
        "quran.info.feature1": "Koran-leseundervisning",
        "quran.info.feature2": "Tajwid-regler og makamer",
        "quran.info.feature3": "Grunnleggende religionskunnskap",
        "quran.info.feature4": "Bønnesurer og bønner",
        "quran.info.feature5": "Islamsk moral og etikette",
        "quran.gallery.title": "🖼️ Korankursbilder",
        "quran.gallery.subtitle": "Bilder tatt mens studentene våre lærer Koranen",
        "quran.gallery.item1.title": "Korantimer",
        "quran.gallery.item1.description": "Studentenes Koran-lesetimer",
        "quran.gallery.item2.title": "Tajwid utdanning",
        "quran.gallery.item2.description": "Tajwid-regler og riktige leseteknikker",
        "quran.gallery.item3.title": "Gruppetimer",
        "quran.gallery.item3.description": "Timer organisert etter aldersgrupper",
        "quran.levels.title": "👥 Aldersgrupper",
        "quran.levels.children.title": "Barnegruppe (6-12 år)",
        "quran.levels.youth.title": "Ungdomsgruppe (13-18 år)",
        "quran.levels.adult.title": "Voksengruppe (18+ år)",
        "quran.benefits.title": "🌟 Fordeler med å lære Koranen",
        "quran.benefits.spiritual.title": "Åndelig utvikling",
        "quran.benefits.spiritual.description": "Å lære Koranen gir åndelig utvikling og nærhet til Allah",
        "quran.benefits.mental.title": "Mental utvikling",
        "quran.benefits.mental.description": "Minneforsterking og økt konsentrasjon",
        "quran.benefits.moral.title": "Moralsk utvikling",
        "quran.benefits.moral.description": "Oppnåelse av islamske verdier og god moral",
        "quran.benefits.social.title": "Sosial binding",
        "quran.benefits.social.description": "Bygge sterkere bånd med samfunnet",
        "quran.registration.title": "🎯 Registrering og deltakelse",
        "quran.registration.description": "Korankurset vårt er åpent for alle aldersgrupper. Du kan kontakte oss for å registrere deg og bli inkludert i klassen som passer ditt barns eller ditt eget nivå.",
        "quran.registration.feature1": "6 år og eldre",
        "quran.registration.feature2": "Gratis utdanning",
        "quran.registration.feature3": "Personlig fremgangssporing",
        "quran.contact.phone": "Telefon: +47 40 14 40 08",
        "quran.contact.email": "Send e-post",
        "quran.visual.title": "Religionsundervisning",
        "quran.visual.description": "Vi støtter barna våre i å utvikle sin religiøse identitet og verdier",

        // About Page
        "about.title": "Om oss",
        "about.mission.title": "Vårt oppdrag",
        "about.mission.text": "Som Diyanet Mevlana Moske er vi her for å tjene det muslimske samfunnet som bor i Norge og holde islamske verdier i live.",
        "about.vision.title": "Vår visjon",
        "about.vision.text": "Vi har som mål å være et sted som bringer samfunnet vårt sammen, en bro mellom religion og kultur.",
        "about.history.title": "Vår historie",
        "about.history.text": "Vår moske ble etablert for å møte behovene til det tyrkiske og muslimske samfunnet i Norge.",

        // Contact Page
        "contact.title": "Kontakt",
        "contact.address.title": "Adresse",
        "contact.address.text": "Stavanger Mosque, Dusavikveien 35, 2 etg<br>4007 Stavanger, Norge",
        "contact.phone.title": "Telefon",
        "contact.phone.text": "+47 40144008",
        "contact.email.title": "E-post",
        "contact.email.text": "leder@mevlanamoske.no",
        "contact.hours.title": "Åpningstider",
        "contact.hours.text": "Mandag - Søndag: 09:00 - 21:00",
        "contact.map.title": "Vår lokasjon",
        "contact.form.title": "Kontakt oss",
        "contact.form.name": "Ditt navn",
        "contact.form.email": "E-post",
        "contact.form.message": "Din melding",
        "contact.form.submit": "Send",

        // Membership Page
        "membership.title": "🤝 Moské Medlemskap",
        "membership.subtitle": "Bli medlem av vår moské og bli en del av vårt samfunn",
        "membership.intro.title": "Velkommen til Vår Moské",
        "membership.intro.text": "Som Diyanet Mevlana Moské-familien er vi svært glade for å se dere blant oss. Som medlem kan du bli informert om moskéens aktiviteter, delta i våre arrangementer og styrke vårt samfunns sterke bånd ytterligere.",
        "membership.benefits.title": "Medlemsfordeler:",
        "membership.benefits.item1": "📧 Regelmessige nyhetsbrev og kunngjøringer",
        "membership.benefits.item2": "🎯 Spesielle arrangement- og programinvitasjoner",
        "membership.benefits.item3": "📚 Prioritert deltakelse i utdanningsprogrammer",
        "membership.benefits.item4": "🤝 Aktiv deltakelse i samfunnsaktiviteter",
        "membership.benefits.item5": "💫 Bidra til moskéens utvikling",
        "membership.form.title": "📝 Medlemskap Søknadsskjema",
        "membership.form.description": "Vennligst fyll ut informasjonen nedenfor fullstendig. Din personlige informasjon vil bli holdt konfidensiell og kun brukt til moskéaktiviteter.",
        "membership.form.type.label": "Operasjonstype",
        "membership.form.type.new": "Nytt Medlemskap",
        "membership.form.type.cancel": "Avbryt Medlemskap",
        "membership.form.firstName.label": "Fornavn",
        "membership.form.firstName.placeholder": "Skriv inn fornavnet ditt",
        "membership.form.lastName.label": "Etternavn",
        "membership.form.lastName.placeholder": "Skriv inn etternavnet ditt",
        "membership.form.email.label": "E-post",
        "membership.form.email.placeholder": "Skriv inn e-postadressen din",
        "membership.form.phone.label": "Telefon",
        "membership.form.phone.placeholder": "Skriv inn telefonnummeret ditt",
        "membership.form.address.label": "Adresse",
        "membership.form.address.placeholder": "Skriv inn full adresse",
        "membership.form.newsletter": "Jeg ønsker å motta nyhetsbrev via e-post",
        "membership.form.privacy": "Jeg godtar behandling av mine personopplysninger",
        "membership.form.submit": "Send Søknad",
        "membership.form.submit.new": "Send Søknad",
        "membership.form.submit.cancel": "Avbryt Medlemskap",
        "membership.form.success": "Din søknad er mottatt! Vi vil kontakte deg så snart som mulig.",
        "membership.form.success.new": "Din søknad er mottatt! Vi vil kontakte deg så snart som mulig.",
        "membership.form.success.cancel": "Din forespørsel om å avbryte medlemskap er mottatt! Den vil bli behandlet så snart som mulig.",
        "membership.form.success.submitted": "Skjemaet ditt er sendt! Vi vil kontakte deg så snart som mulig.",
        "membership.contact.title": "📞 Kontakt",
        "membership.contact.description": "Du kan kontakte oss for spørsmål om medlemskap.",
        "membership.contact.phone": "+47 40144008",
        "membership.contact.email": "leder@mevlanamoske.no",
        "membership.contact.address": "Dusavikveien 35, 2 etg, 4007 Stavanger",

        // Construction Page
        "construction.title": "🕌 Vår Nye Moské Byggeri",
        "construction.subtitle": "Et stort veldedighetsprosjekt for fremtidige generasjoner",

        "construction.intro.title": "Kjære søsken,",
        "construction.intro.text": "Som muslimer bosatt i Stavanger, Norge, var vi nødt til å rive vår moské som vi med stor innsats og ofring eide for 40 år siden. Med Guds tillatelse ønsker vi nå å bygge en større, mer funksjonell moské som vil være til nytte for generasjoner. Men vi har ikke den økonomiske kraften til å gjennomføre denne store og veldedige tjenesten alene. Derfor trenger vi hjelp fra alle våre veldedige søsken, uansett hvor i verden dere befinner dere.",
        "construction.intro.highlight": "Hvert bidrag er en arv som vil vare for fremtidige generasjoner",

        "construction.hadith.arabic": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللَّهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ ﷺ : إِذَا مَاتَ الْإِنْسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلَّا مِنْ ثَلَاثَةٍ: صَدَقَةٍ جَارِيَةٍ، أَوْ عِلْمٍ يُنْتَفَعُ بِهِ، أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ",
        "construction.hadith.source": "(Muslim)",
        "construction.hadith.translation": "\"Når et menneske dør, avbrytes hans gjerninger unntatt tre ting: Kontinuerlig veldedighet (sadaqah jariyah), kunnskap som folk drar nytte av, og en rettskaffent barn som ber for ham.\"",
        "construction.hadith.explanation": "Bidrag til byggingen av vår moské vil være av sadaqah jariyah (kontinuerlig veldedighet). Selv om du bidrar med en murstein, vil du kontinuerlig få del i denne tjenesten; velsignelsen av dine gjerninger vil fortsette.",

        "construction.gallery.title": "🏗️ Prosjektbilder",
        "construction.gallery.subtitle": "Design og planer for vår nye moské",
        "construction.gallery.item1.title": "Hovedfasade",
        "construction.gallery.item1.description": "Moské fasade",
        "construction.gallery.item2.title": "Interiørdesign",
        "construction.gallery.item2.description": "Moské interiør",
        "construction.gallery.item3.title": "Sidevisning",
        "construction.gallery.item3.description": "Moské sidevisning",
        "construction.gallery.item4.title": "Generalplan",
        "construction.gallery.item4.description": "Moské plan",
        "construction.gallery.item5.title": "Detaljvisning",
        "construction.gallery.item5.description": "Arkitektoniske detaljer",
        "construction.gallery.item6.title": "Bønneområde",
        "construction.gallery.item6.description": "Bønneområde",
        "construction.gallery.item7.title": "Landskapsdesign",
        "construction.gallery.item7.description": "Landskapsdesign",
        "construction.gallery.item8.title": "Tilleggsfasiliteter",
        "construction.gallery.item8.description": "Sosiale områder",
        "construction.gallery.item9.title": "Nattvisning",
        "construction.gallery.item9.description": "Nattbelysning",

        "construction.floors.title": "🏢 Prosjekt og Seksjoner",
        "construction.floors.description": "Vår nye moské er planlagt som 4 etasjer. Det vil være et senter hvor både tilbedelse, utdanning og sosiale tjenester vil bli gitt:",
        "construction.floors.floor1.title": "Hovedmoskeen",
        "construction.floors.floor1.description": "Stort tilbedelsesområde hvor menigheten kan be sammen.",
        "construction.floors.floor2.title": "Kvinneseksjon",
        "construction.floors.floor2.description": "Separat bønneseksjon for kvinner og kjøkken — for fellesskapsmåltider og sosiale arrangementer.",
        "construction.floors.floor3.title": "Utdanningsområder",
        "construction.floors.floor3.description": "3 klasserom, bibliotek og kafeteria — for utdanningsaktiviteter for ungdom og barn.",
        "construction.floors.floor4.title": "Leiligheter",
        "construction.floors.floor4.description": "2 leiligheter — for imam og andre tjenestepersoner.",
        "construction.floors.minaret.title": "Minaret",
        "construction.floors.minaret.description": "Et minaret som vil ære vår moské er planlagt.",
        "construction.floors.elevator.title": "Heis",
        "construction.floors.elevator.description": "Det vil være en heis for å sikre enkel tilgang for alle etasjer og funksjonshemmede.",
        "construction.floors.conclusion": "Med denne ordningen vil vår moské ikke bare være et tilbedelsessted, men et senter som gir kunnskap, solidaritet og samfunnstjeneste.",

        "construction.features.title": "🌟 Funksjoner i Vår Nye Moské",
        "construction.features.capacity.title": "Stor Kapasitet",
        "construction.features.capacity.description": "Stor bønnesal som kan ta imot flere av våre menighetsmedlemmer",
        "construction.features.education.title": "Utdanningsområder",
        "construction.features.education.description": "Korankurs og klasserom for våre barn",
        "construction.features.facilities.title": "Moderne Fasiliteter",
        "construction.features.facilities.description": "Vaskeplasser og sosiale områder",
        "construction.features.accessibility.title": "Universell Tilgang",
        "construction.features.accessibility.description": "Passende design for alle aldersgrupper",
        "construction.features.parking.title": "Parkering",
        "construction.features.parking.description": "Stort parkeringsområde",
        "construction.features.community.title": "Samfunnssenter",
        "construction.features.community.description": "Område for arrangementer og sosiale sammenkomster",

        "construction.donation.title": "🤲 Bidra til Dette Veldedige Arbeidet",
        "construction.donation.description": "Hvert bidrag til byggingen av vår nye moské er en arv som vil vare for fremtidige generasjoner. Støtt dette velsignede prosjektet for Guds vilje.",
        "construction.donation.methods.title": "Donasjonsmetoder:",
        "construction.donation.vipps": "Vipps: 95074",
        "construction.donation.bank": "Bankoverføring",
        "construction.donation.contact": "Kontakt oss",
        "construction.donation.vipps.btn": "📱 Doner med Vipps",
        "construction.donation.contact.btn": "📞 Ta Kontakt",
        "construction.donation.qr.text": "Skann QR-koden for rask donasjon",
        "construction.donation.bank.details.title": "💳 Bankoverføring Detaljer",
        "construction.donation.bank.name": "Bank:",
        "construction.donation.bank.account": "Konto nr:",
        "construction.donation.bank.description": "Beskrivelse:",
        "construction.donation.bank.contact": "Kontakt: +47 40 14 40 08",

        "construction.timeline.title": "📅 Prosjekt Tidslinje",
        "construction.timeline.planning.title": "Planleggingsfase",
        "construction.timeline.planning.description": "Prosjektdesign og tillatelser fullført",
        "construction.timeline.planning.date": "2024",
        "construction.timeline.construction.title": "Byggefase",
        "construction.timeline.construction.description": "Vi er i øyeblikket i faseinnsamling og forberedelse",
        "construction.timeline.construction.date": "2025",
        "construction.timeline.opening.title": "Åpning",
        "construction.timeline.opening.description": "Åpning av vår nye moské er planlagt",
        "construction.timeline.opening.date": "2026",

        // Donation Terms
        "donation.terms.title": "Skattefradrag for gaver til Kirke og Moske",
        "donation.terms.short.description": "Kjære medlemmer, når du gir en gave til et godkjent tros- eller livssynssamfunn i Norge kan du få skattefradrag. 🔸 Maksimum fradrag: Opptil 25.000 NOK per år. 🔸 Minimum beløp: Minst 500 NOK per år. 🔸 Personlige opplysninger: Du må oppgi fullt navn og fødselsnummer (11 siffer). 🔸 Automatisk rapportering: Gaven rapporteres til Skatteetaten og fradraget legges automatisk inn i skattemeldingen din. Med din gave til moskeen støtter du samfunnet vårt og får samtidig skattefordel fra staten. 🤲 Din støtte gir både åndelig og økonomisk gevinst.",
        "donation.terms.button": "Vis gavevilkår",
        "donation.terms.intro": "Disse vilkårene regulerer gaver som blir gitt til moskeen fra bidragsytere. Ved å gi en gave, godtar du som bidragsyter de følgende vilkårene:",

        "donation.terms.purpose.title": "1. Formål med gaven",
        "donation.terms.purpose.content": "Gaver som mottas av moskeen skal utelukkende brukes til å støtte moskeens aktiviteter, inkludert, men ikke begrenset til:",
        "donation.terms.purpose.item1": "Drift og vedlikehold av moskeens fasiliteter.",
        "donation.terms.purpose.item2": "Religiøse og sosiale arrangementer.",
        "donation.terms.purpose.item3": "Veldedige formål som er godkjent av moskeen.",

        "donation.terms.voluntary.title": "2. Frivillighet og ingen motytelse",
        "donation.terms.voluntary.content": "Gaver som gis til moskeen er frivillige bidrag. Det gis ingen form for motytelse eller rettigheter som følge av å gi en gave, med mindre dette er uttrykkelig avtalt på forhånd.",

        "donation.terms.payment.title": "3. Betalingsmetoder",
        "donation.terms.payment.content": "Gaver kan gis gjennom følgende metoder:",
        "donation.terms.payment.item1": "Bankoverføring.",
        "donation.terms.payment.item2": "Vipps eller lignende betalingstjenester.",
        "donation.terms.payment.item3": "Kontanter ved personlig oppmøte.",
        "donation.terms.payment.note": "Moskeen tar ikke ansvar for eventuelle gebyrer eller forsinkelser som oppstår i forbindelse med overføringen av gaven.",

        "donation.terms.confirmation.title": "4. Bekreftelse av mottak",
        "donation.terms.confirmation.content": "Bidragsytere vil motta en bekreftelse for gaven dersom dette ønskes. Bekreftelsen kan inneholde opplysninger om gavebeløpet, dato for mottak og formålet gaven skal brukes til.",

        "donation.terms.usage.title": "5. Bruk av gaven",
        "donation.terms.usage.content": "Moskeen forbeholder seg retten til å fordele midlene i samsvar med prioriteringene som bestemmes av moskeens styre. Øremerkede gaver vil bli brukt til det spesifiserte formålet, så langt det lar seg gjøre.",

        "donation.terms.refund.title": "6. Refusjon",
        "donation.terms.refund.content": "Gaver er som hovedregel ikke refunderbare. Dersom det oppstår en feil ved overføringen, ber vi bidragsytere kontakte moskeen umiddelbart for å rette opp i situasjonen.",

        "donation.terms.privacy.title": "7. Personvern",
        "donation.terms.privacy.content": "Personopplysninger som samles inn i forbindelse med gaver, vil bli behandlet i samsvar med gjeldende personvernlovgivning. Opplysningene vil kun bli brukt for administrasjon av gaven og vil ikke bli delt med tredjeparter uten samtykke.",

        "donation.terms.changes.title": "8. Endringer i vilkårene",
        "donation.terms.changes.content": "Moskeen forbeholder seg retten til å endre disse vilkårene. Eventuelle endringer vil bli publisert på moskeens nettsider eller gjort kjent på annen hensiktsmessig måte.",

        "donation.terms.contact.title": "9. Kontaktinformasjon",
        "donation.terms.contact.content": "For spørsmål om gaver eller disse vilkårene, kan moskeen kontaktes på:",
        "donation.terms.contact.email": "E-post: leder@Mevlanamoske.no",
        "donation.terms.contact.phone": "Telefon: +47 40144008",
        "donation.terms.contact.address": "Adresse: Verksgt 41 4013 Stavanger",
        "donation.terms.contact.org": "Organisasjonsnummer: 971 490 942",

        "donation.terms.acceptance": "Ved å gi en gave bekrefter du at du har lest og forstått disse vilkårene, og at du godtar dem i sin helhet.",

        // Donation Terms PDF
        "donation.terms.pdf.fallback": "PDF-viseren støtter ikke denne filen.",
        "donation.terms.pdf.download": "Klikk her for å laste ned",
        "donation.terms.pdf.open": "Åpne i ny fane",
        "donation.terms.pdf.download.btn": "Last ned",

        // Prayer Times
        "prayer.page.title": "Bønnetider",
        "prayer.page.subtitle": "Daglige bønnetider for Stavanger - Norge",
        "prayer.location": "Stavanger, Norge",
        "prayer.today.title": "Dagens Bønnetider",
        "prayer.fajr": "Fajr",
        "prayer.sunrise": "Soloppgang",
        "prayer.dhuhr": "Dhuhr",
        "prayer.asr": "Asr",
        "prayer.maghrib": "Maghrib",
        "prayer.isha": "Isha",
        "prayer.next.title": "Neste Bønn",
        "prayer.weekly.title": "Ukentlige Bønnetider",
        "prayer.table.date": "Dato",
        "prayer.table.fajr": "Fajr",
        "prayer.table.sunrise": "Soloppgang",
        "prayer.table.dhuhr": "Dhuhr",
        "prayer.table.asr": "Asr",
        "prayer.table.maghrib": "Maghrib",
        "prayer.table.isha": "Isha",
        "prayer.notes.title": "Viktige Merknader",
        "prayer.notes.calculation": "Tidene er beregnet i henhold til Diyanet kalkulasjonsmetode.",
        "prayer.notes.location": "Stavanger koordinater: 58.9937° N, 5.7275° Ø",
        "prayer.notes.accuracy": "Tidene er omtrentlige og kan ha ±2 minutters toleranse.",
        "prayer.notes.update": "Tidene oppdateres automatisk.",

        // Footer
        "footer.welcome": "Velkommen til Diyanet Mevlana Moske",
        "footer.description": "Som Diyanet Mevlana Moske i Stavanger er vi stolte av å tjene vårt muslimske samfunn.",
        "footer.org.number": "Org.nr: 971 490 942",
        "footer.quick.links": "Hurtigkoblinger",
        "footer.support": "Støtte",
        "footer.vipps.donation": "Vipps donasjon: 95074",
        "footer.mosque.name": "Diyanet Mevlana Moske",
        "footer.contact.title": "Kontakt",
        "footer.contact.phone": "Telefon:",
        "footer.contact.email": "E-post:",
        "footer.contact.address": "Adresse:",
        "footer.contact.address.text": "Dusavikveien 35 4007, Stavanger, Norway",
        "footer.map.title": "Lokasjon",
        "footer.copyright": "© 2025 Diyanet Mevlana Moske. Alle rettigheter forbeholdt."
    }
};

// Varsayılan dil
const DEFAULT_LANGUAGE = 'no';

// Mevcut dili localStorage'dan al veya varsayılan kullan
let currentLanguage = localStorage.getItem('selectedLanguage') || DEFAULT_LANGUAGE;
